baseURL = "https://insilichem.com"
languageCode = "en-us"
title = "InsiliChem"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.nav]]
name    = "About us"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 3
[[menu.nav]]
name    = "Publications"
url     = "publications"
weight  = 4
[[menu.nav]]
name    = "Research"
url     = "research"
weight  = 5
[[menu.nav]]
name    = "Services"
url     = "services"
weight  = 6
[[menu.nav]]
name    = "Software"
url     = "software"
weight  = 7

# Site Params
[params]
home = "Home"
logo = "/favicon.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "InsiliChem"
description = "for the study and design of chemobiotechnological systems"
# button
btn     = true
btnText = "Know more"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "Molecular Modeling"
[[params.banner.flipText]]
title   = "Computational Chemistry"
[[params.banner.flipText]]
title   = "Scientific Software Development"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "Led by Dr. Jean-Didier Maréchal, InsiliChem is a team that focuses on the modeling of systems at the interface between <strong>chemistry and biology</strong>. Our primary interests are chemobiological hybrids like artificial enzymes, biosensors and biomarkers and more particularly those involving transition metal moieties. We have a large network of collaborations worldwide both with experimental and theoretical groups leader in these fields.<br />We also intensively work on structural bioinformatics and computational chemistry methodological developments that could sustain our investigation and our multi-scale procedures. Most of our efforts are performed using Python as a principal scripting language. In the last months we have published more than 25 new modeling packages in GitHub. Most of them are GUIs designed for UCSF Chimera, with whom we have a long and strong collaboration."
image   = "/images/logo_green.svg"

# Call to Action
[params.cta]
enable  = true
title   = "Get in touch"
content = "We are located at the Chemistry Department of the Universitat Autònoma de Barcelona (Spain)"
btnText = "Contact us"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Check our <a href='https://scholar.google.com/citations?user=1hjLUfgAAAAJ' target='_blank' >latest publications</a>."

# social icon
[[params.socialIcon]]
icon = "ion-social-github"
url = "https://github.com/insilichem"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/insilichem"
